### ISSUE TITLE
Pass through arguments to pylint

### ISSUE THREAD

**Issue by DamienBth** [MasterOdin/pylint_runner#9]
Hello :) 

Before all, thanks for this tool very convenient !

I tested argument like --ignore on pylint_runner but it is not passed to pylint.
It would be really helping to have this feature for my projects. Do you think it could be done ?

Thank you.

**Comment by oferz** [comment]
Having all arguments pass through would be useful. For example, I'd like to use pylint_runner but with a different output format that my CI tool can read.

**Comment by MasterOdin** [comment]
Done in 7ef7c395972ff5898b54f8f49c256e39d99c4b03. Any unused argument to pylint_runner is now passed through directly to pylint.

**Comment by MasterOdin** [comment]
Note, this is in the freshly released 0.6.0
